services:
  mysql-orders:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_orders:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10

  phpmyadmin-orders:
    image: phpmyadmin:latest
    restart: unless-stopped
    depends_on:
      mysql-orders:
        condition: service_healthy
    environment:
      PMA_HOST: mysql-orders
      PMA_PORT: 3306
    ports:
      - "8080:80"

volumes:
  mysql_data_orders:
    external: true